############
# sclForum #
############
index:
  is_secure: false

show:
  is_secure: false

new:
  is_secure: true
  credentials: [scl_forum_create]

create:
  is_secure: true
  credentials: [scl_forum_create]

edit:
  is_secure: true
  credentials: [scl_forum_update]

update:
  is_secure: true
  credentials: [scl_forum_update]

delete:
  is_secure: true
  credentials: [scl_forum_delete]