<?php

/**
 * PluginsclForumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsclForumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsclForumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsclForum');
    }
}