<?php

/**
 * PluginsclTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsclTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsclTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsclTopic');
    }
}