<?php

/**
 * PluginsclPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsclPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsclPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsclPost');
    }
}