sclPost:
  actAs:
    Timestampable: ~
    Blameable: ~
    SoftDelete: ~
    Versionable: ~
    Searchable:
      fields: [title,body]
  columns:
    forum_id:
      type: integer
      notnull: true
    topic_id:
      type: integer
      notnull: true
    title:
      type: string
      length: 255
    body:
      type: clob
      notnull: true
    ip_address:
      type: string
      length: 32
#  indexes:
  relations:
    CreatedByUser:
      class: sfGuardUser
      local: created_by
      foreign: id
    UpdatedByUser:
      class: sfGuardUser
      local: updated_by
      foreign: id
    Forum:
      class: sclForum
      local: forum_id
      foreign: id
    Topic:
      class: sclTopic
      local: topic_id
      foreign: id